export enum TranslateKeys {
  AboutMeApp_Completed = 'AboutMeApp_Completed',
  AboutMeApp_CurriculumVitae = 'AboutMeApp_CurriculumVitae',
  AboutMeApp_Projects = 'AboutMeApp_Projects',
  AboutMeApp_Projects_Repositories = 'AboutMeApp_Projects_Repositories',
  AboutMeApp_Projects_Showcase = 'AboutMeApp_Projects_Showcase',
  AboutMeApp_ShortAboutMeText = 'AboutMeApp_ShortAboutMeText',
  AboutMeApp_Technologies = 'AboutMeApp_Technologies',
  AboutMeApp_Welcome = 'AboutMeApp_Welcome',
  Apps_AboutMe = 'Apps_AboutMe',
  Apps_Apps = 'Apps_Apps',
  Apps_Blog = 'Apps_Blog',
  Apps_Contact = 'Apps_Contact',
  Common_Back = 'Common_Back',
  Common_Complete = 'Common_Complete',
  Common_Next = 'Common_Next',
  Power_AreYouSureToRestart = 'Power_AreYouSureToRestart',
  Power_AreYouSureToShutdown = 'Power_AreYouSureToShutdown',
  Power_Power = 'Power_Power',
  Commands_Restart = 'Commands_Restart',
  Commands_Shutdown = 'Commands_Shutdown',
  System_System = 'System_System',
}
