export const PERFORMANCE_LIMITS = {
  MAX_DIRECTORY_ENTRIES: 1000,
  MAX_RECURSION_DEPTH: 100,
  MAX_OPERATION_RETRIES: 3,
  OPERATION_TIMEOUT_MS: 30000,
  BATCH_SIZE: 50,
  DEBOUNCE_DELAY_MS: 300,
} as const;
